exports.Classlist = [
  // { tag: 'new_blhy', name: '玻璃行业' },
  // { tag: 'new_cbzz', name: '船舶制造' },
  // { tag: 'new_cmyl', name: '传媒娱乐' },
  // { tag: 'new_dlhy', name: '电力行业' },
  // { tag: 'new_dqhy', name: '电器行业' },
  // { tag: 'new_dzqj', name: '电子器件' },
  // { tag: 'new_dzxx', name: '电子信息' },
  // { tag: 'new_fdc', name: '房地产' },
  // { tag: 'new_fdsb', name: '发电设备' },
  // { tag: 'new_fjzz', name: '飞机制造' },
  // { tag: 'new_fzhy', name: '纺织行业' },
  // { tag: 'new_fzjx', name: '纺织机械' },
  // { tag: 'new_fzxl', name: '服装鞋类' },
  // { tag: 'new_glql', name: '公路桥梁' },
  // { tag: 'new_gsgq', name: '供水供气' },
  // { tag: 'new_gthy', name: '钢铁行业' },
  // { tag: 'new_hbhy', name: '环保行业' },
  //   { tag: 'new_hghy', name: '化工行业' },
  //   { tag: 'new_hqhy', name: '化纤行业' },
  //   { tag: 'new_jdhy', name: '家电行业' },
  //   { tag: 'new_jdly', name: '酒店旅游' },
  //   { tag: 'new_jjhy', name: '家具行业' },
  //   { tag: 'new_jrhy', name: '金融行业' },
  // { tag: 'new_jtys', name: '交通运输' },
  // { tag: 'new_jxhy', name: '机械行业' },
  // { tag: 'new_jzjc', name: '建筑建材' },
  // { tag: 'new_kfq', name: '开发区' },
  // { tag: 'new_ljhy', name: '酿酒行业' },
  // { tag: 'new_mtc', name: '摩托车' },
  // { tag: 'new_mthy', name: '煤炭行业' },
  // { tag: 'new_nlmy', name: '农林牧渔' },
  // { tag: 'new_nyhf', name: '农药化肥' },
  // { tag: 'new_qczz', name: '汽车制造' },
  // { tag: 'new_qtxy', name: '其它行业' },
  // { tag: 'new_slzp', name: '塑料制品' },
  // { tag: 'new_snhy', name: '水泥行业' },
  // { tag: 'new_sphy', name: '食品行业' },
  // { tag: 'new_stock', name: '次新股' },
  // { tag: 'new_swzz', name: '生物制药' },
  // { tag: 'new_sybh', name: '商业百货' },
  // { tag: 'new_syhy', name: '石油行业' },
  // { tag: 'new_tchy', name: '陶瓷行业' },
  // { tag: 'new_wzwm', name: '物资外贸' },
  // { tag: 'new_ylqx', name: '医疗器械' },
  // { tag: 'new_yqyb', name: '仪器仪表' },
  // { tag: 'new_ysbz', name: '印刷包装' },
  { tag: 'new_ysjs', name: '有色金属' },
  { tag: 'new_zhhy', name: '综合行业' },
  { tag: 'new_zzhy', name: '造纸行业' }
]
